### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [pacmandoh/omz-theme-pacmandoh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by pacmandoh** [comment]
Hey @unixorn , It's a great honor for me to add my theme to your awsomes list! I will add screenshots later. ❤️

**Comment by unixorn** [comment]
Thanks! Either close this issue when you've added them and I'll add it to the list, or you can PR directly into [the](https://github.com/unixorn/awesome-zsh-plugins), whatever's easiest for you.

**Comment by pacmandoh** [comment]
No problem, I'm trying to improve the production.

**Comment by pacmandoh** [comment]
> me to

@unixorn  Sorry, I just realized that I sent the wrong message. "It is an honor for me 😅 ". I have rewritten the theme here, and I will PR after I improve the document.
